apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"operator.openshift.io/v1","kind":"IngressController","metadata":{"annotations":{},"creationTimestamp":"2022-06-18T07:35:21Z","finalizers":["ingresscontroller.operator.openshift.io/finalizer-ingresscontroller"],"generation":11,"name":"default","namespace":"openshift-ingress-operator","resourceVersion":"29284021","uid":"fd43dc7a-31d1-4458-85ad-f431f799997f"},"spec":{"clientTLS":{"clientCA":{"name":""},"clientCertificatePolicy":""},"httpCompression":{},"httpEmptyRequestsPolicy":"Respond","httpErrorCodePages":{"name":""},"replicas":2,"tuningOptions":{}},"status":{"availableReplicas":2,"conditions":[{"lastTransitionTime":"2022-06-18T07:35:28Z","reason":"Valid","status":"True","type":"Admitted"},{"lastTransitionTime":"2022-08-11T17:52:25Z","status":"True","type":"PodsScheduled"},{"lastTransitionTime":"2022-07-20T23:51:36Z","message":"The deployment has Available status condition set to True","reason":"DeploymentAvailable","status":"True","type":"DeploymentAvailable"},{"lastTransitionTime":"2022-07-20T23:51:36Z","message":"Minimum replicas requirement is met","reason":"DeploymentMinimumReplicasMet","status":"True","type":"DeploymentReplicasMinAvailable"},{"lastTransitionTime":"2022-08-11T17:52:55Z","message":"All replicas are available","reason":"DeploymentReplicasAvailable","status":"True","type":"DeploymentReplicasAllAvailable"},{"lastTransitionTime":"2022-06-18T07:35:28Z","message":"The configured endpoint publishing strategy does not include a managed load balancer","reason":"EndpointPublishingStrategyExcludesManagedLoadBalancer","status":"False","type":"LoadBalancerManaged"},{"lastTransitionTime":"2022-06-18T07:35:28Z","message":"No DNS zones are defined in the cluster dns config.","reason":"NoDNSZones","status":"False","type":"DNSManaged"},{"lastTransitionTime":"2022-07-20T23:51:36Z","status":"True","type":"Available"},{"lastTransitionTime":"2022-06-18T07:35:28Z","status":"False","type":"Progressing"},{"lastTransitionTime":"2022-07-28T17:04:09Z","status":"False","type":"Degraded"},{"lastTransitionTime":"2022-06-18T07:35:28Z","message":"IngressController is upgradeable.","reason":"Upgradeable","status":"True","type":"Upgradeable"},{"lastTransitionTime":"2022-07-28T17:04:08Z","message":"Canary route checks for the default ingress controller are successful","reason":"CanaryChecksSucceeding","status":"True","type":"CanaryChecksSucceeding"}],"domain":"apps.ocp410.mclabs.us","endpointPublishingStrategy":{"hostNetwork":{"protocol":"TCP"},"type":"HostNetwork"},"observedGeneration":11,"selector":"ingresscontroller.operator.openshift.io/deployment-ingresscontroller=default","tlsProfile":{"ciphers":["ECDHE-ECDSA-AES128-GCM-SHA256","ECDHE-RSA-AES128-GCM-SHA256","ECDHE-ECDSA-AES256-GCM-SHA384","ECDHE-RSA-AES256-GCM-SHA384","ECDHE-ECDSA-CHACHA20-POLY1305","ECDHE-RSA-CHACHA20-POLY1305","DHE-RSA-AES128-GCM-SHA256","DHE-RSA-AES256-GCM-SHA384","TLS_AES_128_GCM_SHA256","TLS_AES_256_GCM_SHA384","TLS_CHACHA20_POLY1305_SHA256"],"minTLSVersion":"VersionTLS12"}}}
  creationTimestamp: "2022-06-18T07:35:21Z"
  finalizers:
  - ingresscontroller.operator.openshift.io/finalizer-ingresscontroller
  generation: 12
  name: default
  namespace: openshift-ingress-operator
  resourceVersion: "29291375"
  uid: fd43dc7a-31d1-4458-85ad-f431f799997f
spec:
  clientTLS:
    clientCA:
      name: ""
    clientCertificatePolicy: ""
  httpCompression: {}
  httpEmptyRequestsPolicy: Respond
  httpErrorCodePages:
    name: ""
  replicas: 2
  namespaceSelector:
    matchExpressions:
    - key: routeshard
      operator: DoesNotExist
  tuningOptions: {}
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2022-06-18T07:35:28Z"
    reason: Valid
    status: "True"
    type: Admitted
  - lastTransitionTime: "2022-08-11T18:10:51Z"
    status: "True"
    type: PodsScheduled
  - lastTransitionTime: "2022-07-20T23:51:36Z"
    message: The deployment has Available status condition set to True
    reason: DeploymentAvailable
    status: "True"
    type: DeploymentAvailable
  - lastTransitionTime: "2022-07-20T23:51:36Z"
    message: Minimum replicas requirement is met
    reason: DeploymentMinimumReplicasMet
    status: "True"
    type: DeploymentReplicasMinAvailable
  - lastTransitionTime: "2022-08-11T18:11:20Z"
    message: All replicas are available
    reason: DeploymentReplicasAvailable
    status: "True"
    type: DeploymentReplicasAllAvailable
  - lastTransitionTime: "2022-06-18T07:35:28Z"
    message: The configured endpoint publishing strategy does not include a managed
      load balancer
    reason: EndpointPublishingStrategyExcludesManagedLoadBalancer
    status: "False"
    type: LoadBalancerManaged
  - lastTransitionTime: "2022-06-18T07:35:28Z"
    message: No DNS zones are defined in the cluster dns config.
    reason: NoDNSZones
    status: "False"
    type: DNSManaged
  - lastTransitionTime: "2022-07-20T23:51:36Z"
    status: "True"
    type: Available
  - lastTransitionTime: "2022-06-18T07:35:28Z"
    status: "False"
    type: Progressing
  - lastTransitionTime: "2022-07-28T17:04:09Z"
    status: "False"
    type: Degraded
  - lastTransitionTime: "2022-06-18T07:35:28Z"
    message: IngressController is upgradeable.
    reason: Upgradeable
    status: "True"
    type: Upgradeable
  - lastTransitionTime: "2022-07-28T17:04:08Z"
    message: Canary route checks for the default ingress controller are successful
    reason: CanaryChecksSucceeding
    status: "True"
    type: CanaryChecksSucceeding
  domain: apps.ocp410.mclabs.us
  endpointPublishingStrategy:
    hostNetwork:
      protocol: TCP
    type: HostNetwork
  observedGeneration: 12
  selector: ingresscontroller.operator.openshift.io/deployment-ingresscontroller=default
  tlsProfile:
    ciphers:
    - ECDHE-ECDSA-AES128-GCM-SHA256
    - ECDHE-RSA-AES128-GCM-SHA256
    - ECDHE-ECDSA-AES256-GCM-SHA384
    - ECDHE-RSA-AES256-GCM-SHA384
    - ECDHE-ECDSA-CHACHA20-POLY1305
    - ECDHE-RSA-CHACHA20-POLY1305
    - DHE-RSA-AES128-GCM-SHA256
    - DHE-RSA-AES256-GCM-SHA384
    - TLS_AES_128_GCM_SHA256
    - TLS_AES_256_GCM_SHA384
    - TLS_CHACHA20_POLY1305_SHA256
    minTLSVersion: VersionTLS12
