apiVersion: v1
items:
- apiVersion: operator.openshift.io/v1
  kind: IngressController
  metadata:
    name: shard-1
    namespace: openshift-ingress-operator
  spec:
    domain: shard-1.ocp410.mclabs.us
    nodePlacement:
      nodeSelector:
        matchLabels:
          node-role.kubernetes.io/worker: ""
    namespaceSelector:
      matchLabels:
        routeshard: shard-1
#    routeSelector:
#    matchLabels:
#      routeshard: shard-1
  status: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
